name: Code Climate Coverage

on: 
  push:
    branches:
      - prod

  pull_request:
    branches: 
    - prod

jobs: 
  PublishCodeCoverage:
    runs-on: ubuntu-latest
    steps:
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v4.0.0
        env:
          CC_TEST_REPORTER_ID: $ {{ secrets.CC_REPORTER_ID }}
        with:
          coverageCommand: npm run coverage
          debug: true