name: jsdoc
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      uses: andstor/jsdoc-action@v3
      with:
        source_dir: ./source
        recurse: true
        output_dir: ./docs
        front_page: README.md
        template: clean-jsdoc-theme
    
    - name: Commit Docs
      uses: EndBug/add-and-commit@v9
      with:
        auhor_name: Github Actions
        author_email: noreply@github.com
        message: 'CI: Automated JSDocs build push'
        add: 'docs/*'

    #   run: |
    #     echo ${{ github.ref }}
    #     git add ./docs
    #     git config --local user.email "bot@users.noreply.github.com"
    #     git config --local user.name "bot"
    #     git commit -m "CI: Automated build push" -a | exit 0
        
    # - name: Push changes
    #   if: github.ref == 'refs/heads/master'
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}