name: Unit Tests
on:
  push:
    branches:
      - HoroscopeDisplay-Add-to-me
      - prod

  #pull_request:
    #branches: [master]
  pull_request:
    branches: [prod]
jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test
