name: Unit Tests

on:
  push:
    branches:
      - prod
    
  pull_request:
    branches: [prod]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          npm install 
          npm test